name: Hello World Workflow

on:
  push:
    branches:
      - main # Make sure this matches your default branch name

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions!"